# Copyright: Ankitects Pty Ltd and contributors
# License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
"""Regenerate the bundled AnkiDroid mobile page from the desktop web + scoring
sources.

The mobile dashboard/practice page (AnkiDroid/src/main/assets/vantage/index.html)
is GENERATED by render.build_mobile_page, never hand-edited (see anki-android/
VANTAGE.md). Run this after any change to vantage_addon/web/* so desktop and mobile
stay at parity.

It preserves the page's baked fallback dashboard dict (the host injects live scores
after load; the baked data is only the offline fallback) by lifting the existing
window.__VANTAGE__ = {...} out of the current asset and feeding it back in, so the
only thing that changes is the inlined CSS/JS. If no baked data can be read it falls
back to None, which still yields a valid page (the host injects real data).

Usage:  python vantage_tools/build_mobile_asset.py
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import pathlib
import sys

_ANKI = pathlib.Path(__file__).resolve().parents[1]
_PROJECTS = _ANKI.parent
_ASSET = (
    _PROJECTS
    / "anki-android"
    / "AnkiDroid"
    / "src"
    / "main"
    / "assets"
    / "vantage"
    / "index.html"
)


def _load_render():
    path = _ANKI / "vantage_addon" / "render.py"
    spec = importlib.util.spec_from_file_location("vantage_render", path)
    assert spec and spec.loader, path
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _extract_baked(html: str) -> dict | None:
    """Lift the baked window.__VANTAGE__ = {...} fallback out of an existing page."""
    marker = "window.__VANTAGE__ = "
    i = html.find(marker)
    if i == -1:
        return None
    i = html.find("{", i)
    if i == -1:
        return None
    try:
        data, _end = json.JSONDecoder().raw_decode(html, i)
        return data
    except Exception:
        return None


def _generate() -> tuple[str, dict | None]:
    """Build the mobile page in memory from the CURRENT desktop source, lifting
    the baked fallback out of the existing asset (the exact path the writer uses).
    Writes nothing. Both the writer and --check go through here, so the staleness
    check can never disagree with the real regenerator."""
    render = _load_render()
    old = _ASSET.read_text(encoding="utf-8") if _ASSET.exists() else ""
    data = _extract_baked(old)
    page = render.build_mobile_page(data)
    return page, data


def _write() -> None:
    page, data = _generate()
    _ASSET.parent.mkdir(parents=True, exist_ok=True)
    _ASSET.write_text(page, encoding="utf-8")
    print(f"wrote {_ASSET} ({len(page)} bytes)")
    print(f"baked fallback data: {'preserved' if data is not None else 'none (host injects live)'}")
    print(f"'Full-length exam' present: {'Full-length exam' in page}")


def _check() -> int:
    """Dry-run staleness check: regenerate the page in memory and compare its
    sha256 to the bundled asset on disk. Prints 'IN SYNC <hash>' and returns 0
    when current, or 'STALE' + both hashes and returns 1 when the desktop source
    has drifted ahead of the bundled asset. Writes nothing."""
    page, _data = _generate()
    generated = hashlib.sha256(page.encode("utf-8")).hexdigest()
    on_disk = hashlib.sha256(_ASSET.read_bytes()).hexdigest() if _ASSET.exists() else None
    if on_disk == generated:
        print(f"IN SYNC {generated}")
        return 0
    print("STALE")
    print(f"  generated (from current desktop source): {generated}")
    print(f"  bundled mobile asset:                    {on_disk}")
    return 1


def main() -> None:
    if "--check" in sys.argv[1:]:
        raise SystemExit(_check())
    _write()


if __name__ == "__main__":
    main()
